---
title: "Intro to ggplot2 - Ian Lyons"
author: "Ian Lyons"
date: "1/20/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(gghighlight)
library(ggpubr)
```

## Read in Tax Expenditure and Federal Outlays Data

* Source for tax expenditures on the Treasury Department Website: 
https://home.treasury.gov/policy-issues/tax-policy/tax-expenditures

* Source for federal outlays on the Office of Management and Budget website: 
https://www.whitehouse.gov/omb/supplemental-materials/
```{}
base_df <- read_csv(file = 'tax_expenditures_18to28_renamed.csv')

budg_2019 <- read_csv(file = 'outlays-fy2019.csv')
```


## Reshape Tax Expenditure Dataframe For Plot 1

* Create a long-form version of the tax expenditures dataset to use in a time-series plot. That is, create one row for each category, detail, and fiscal year. 
* Drop the cumulative 'FY2019_to_2028' column since I won't be using it.

```{}
tax_long <- gather(base_df, fiscal_year, expenditure, '2018':'2028', factor_key=TRUE)
tax_long$FY2019_to_2028 <- NULL
```


## Plot 1: Projected Tax Expenditures By Policy Category
* Create a time-series dataset so that tax expenditures can be compared over the fiscal years included.
* Convert the expenditure column to be in billions of dollars by dividing by 1000 (the tax expenditures dataset is in millions of dollars by default).

```{}
time_series <- tax_long %>% select(fiscal_year, Category, expenditure) %>%
                  group_by(fiscal_year, Category) %>%
                  tally(expenditure)

time_series <- mutate(.data = time_series, amount_billions = n/1000)
time_series$n <- NULL

bar_to_plot <- ggplot(data=time_series, aes(x=fiscal_year, y=amount_billions, color=Category, fill=Category)) + geom_col()

plot1 <- bar_to_plot + 
    scale_y_continuous(name = "Tax Expenditures in Billions of Nominal Dollars", 
         labels =c('$0', '$433', '$866', '$1,300', '$1,733', '$2,166', '$2,600') 
         , breaks=c(0, 433, 866, 1300, 1733, 2166, 2600), limits = c(0,2600)) + 
    scale_x_discrete(name='Fiscal Year') + 
    
    labs(title = "US Federal Government Tax Expenditures, 2018-2028", 
         subtitle = "The United States spends trillions of dollars on tax loopholes each year",
         caption = "Source: United States. Department of Treasury. Tax Policy: Tax Expenditures. \n 
         * These estimates are made relative to current law as of July 1, 2018", 
         x = "Fiscal Year" + 
             
        theme(plot.title = element_text(color="black", size=14, face="bold", hjust = 0.5),
          plot.subtitle = element_text(color="black", size=12, hjust =0.5),
          axis.title.x = element_text(color="black", size=12),
          axis.title.y = element_text(color="black", size=12),
          plot.caption = element_text(color="black", size=8, face="italic")
          )
    )
```

<br><br><br><br>

# Prep For Plots 2 & 3: Group by agency name and sum expenditures within the same agency and year.

* Create a long-form version of the outlays dataset to use in a time-series plot. That is, create one row for each line item (agency name, bureau name, account name, etc.) and fiscal year. 

```{}

budget_longform <- gather(budg_2019, fiscal_year, expenditure, '1962':'2018', factor_key=TRUE)

## Keep only descriptive column names rather than codes. 
keep_cols <- c('Agency Name', 'Bureau Name', 'Account Name', 'Treasury Agency Code', 'Subfunction Title', 'BEA Category', 'Grant/non-grant split' , 'On- or Off- Budget', 'fiscal_year', 'expenditure')

budget_longform <- budget_longform[keep_cols]
```

* Take the reshaped longform budget data and group by fiscal year and agency name. 

```{}
outlays <- budget_longform %>% select(fiscal_year, `Agency Name`, expenditure) %>%
			group_by(fiscal_year, `Agency Name`) %>%
			tally(expenditure)

## Give the expenditures column a descriptive name			
outlays <- mutate(.data = outlays, dollars_thousands = n)
outlays$n <- NULL

## Rename `Agency Name` in snake case.
colnames(outlays)[2] <- 'agency_name'

```

<br><br>

## Plot 2: FacetWrap Grid Showing the Annual Outlays 1995-2018 of Some of the Largest Agencies & Departments

* Filter to the fiscal years 1995 to 2018.
* Filter to only the 12 agencies/departments with the largest budgets.

```{}
outlays %>%
  filter(fiscal_year  %in% c(1995:2018)) %>%
  filter(agency_name %in% c("Social Security Administration","Department of Health and Human Services","Department of Defense--Military Programs"
	      ,"Department of the Treasury","Department of Agriculture", "Department of Veterans Affairs", "Department of Labor", 
	      "Office of Personnel Management", "Department of Transportation", "Department of Education", "Other Defense Civil Programs", 
	      "Department of Housing and Urban Development")) %>%
	      
  ggplot(aes(x = fiscal_year, y = dollars_thousands, fill = agency_name)) +
  geom_histogram(stat = "sum") + 
  facet_wrap(~agency_name) +
  scale_y_continuous(name = "Outlays (Thousands of US Dollars)", labels = scales::dollar) +

  labs(title = "Departmental Outlays Since 1995, Top 12 Departments By Outlays",
       subtitle = "Some agencies, like the Dept of Defense and the Treasury, have experienced significant shifts in outlays since 1995.",
       caption="Source: United States. Office of Management and Budget. Public Budget Database.",
       x = "Fiscal Year",
       y = "Outlays In Thousands of US Dollars ") + 
       
  theme(axis.text.x = element_text(angle = 90),
        strip.text = element_text(face = "plain", 
        size = rel(0.9)),
        plot.title = element_text(color="black", size=14, face="bold", hjust = 0.5),
        plot.subtitle = element_text(color="black", size=12, hjust =0.5),
        axis.title.x = element_text(color="black", size=14),
        axis.title.y = element_text(color="black", size=14),
        plot.caption = element_text(color="black", size=8, face="italic"),
        legend.position="none"
        )
```


<br><br>

# Plot 3: Federal Government Outlays by Agency By Year
* Use the same outlays dataset. 
* I take the federal government outlays dataset and choose the top 8 departments by total amount spent over the last 9 years.
* Limit the years to just the last 9 so that the point plot is comprehensible. 
* Group by agency name and fiscal year. 

```{}
outlays %>%
  filter(agency_name %in% c("Social Security Administration","Department of Health and Human Services","Department of Defense--Military Programs", "Department of the Treasury","Department of Agriculture", "Department of Veterans Affairs", "Department of Labor", "Office of Personnel Management")) %>% 
	
	filter(fiscal_year %in% c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018)) %>%
	
  group_by(agency_name, fiscal_year) %>%
  summarize(dollars_thousands = sum(dollars_thousands)) %>%
  
      ggplot(aes(x = fiscal_year, y = dollars_thousands, color = agency_name, group=agency_name)) +
      geom_point() + geom_line() + ggpubr::rotate_x_text() +
      scale_y_continuous(name = "Outlays (Thousands of US Dollars)", labels = scales::dollar) +
        
        labs(title = "Federal Government Outlays By Agency By Year (Top 8 Agencies By Outlays)",
          subtitle = "The Department of Health and Human Services and the Social Security Administration Had the Largest Outlays",
          caption = "Source: United States. Office of Management and Budget. Public Budget Database.",
          x = "Year",
          y = "Outlays (Thousands of US Dollars)" +              
            
          theme(plot.title = element_text(color="black", size=14, face="bold", hjust = 0.5),
              plot.subtitle = element_text(color="black", size=12, hjust =0.5),
              axis.title.x = element_text(color="black", size=14, angle = 90),
              axis.title.y = element_text(color="black", size=14),
              plot.caption = element_text(color="black", size=8, face="italic")
              )
        )
```


