---
title: "Maps Maps Maps"
author: "Ian Lyons"
date: "2/5/2019"
output: 
  html_document: 
    fig_caption: yes
    fig_height: 8.5
    fig_width: 11
    code_folding: hide
urlcolor: blue
---

```{r setup, echo=FALSE, include=FALSE}
library(tidyverse)
library(rmarkdown)
library(here)
library(gghighlight)
library(ggpubr)
library(formatR)
library(tinytex)
library(scales)
library(ggthemes)
library(extrafont)
library(RColorBrewer)
library(treemapify)
library(ggplot2)
```

```{r}
cbo_spend <- read_csv(file = 'raw_data/CBO_SPENDING_PROJECTION.csv')
cbo_long <- cbo_spend %>% gather(fiscal_year, expenditure, '2019':'2029', factor_key = TRUE)
colnames(cbo_long) <- c("Treasury ID Number", 
                        "Title", 
                        "Category", 
                        "CBO Major Category", 
                        "Agency Name",
                        "Bureau Name", 
                        "Function", 
                        "Subfunction", 
                        "Off/On-budget", 
                        "fiscal_year", 
                        "Expenditure")

#Get the agencies that we can make apples to apples comparisons for. 
agencies_common <- unique((budget_longform %>% filter(`Agency Name` %in% cbo_long$`Agency Name`))$`Agency Name`) 

cbo_outlays <- cbo_long %>% 
  select(fiscal_year, `Agency Name`, Expenditure) %>% 
  group_by(fiscal_year, `Agency Name`) %>% 
  summarize(projection = sum(Expenditure, na.rm = TRUE))
# Put the cbo spending numbers in the name units as OMB spending numbers
cbo_outlays <- cbo_outlays %>% mutate(projection = projection*1000) 
cbo_outlays <-  cbo_outlays %>% mutate(office = 'CBO')

omb_outlays <- outlays %>% filter(fiscal_year %in% c(2019, 2020, 2021, 2022, 2023))
colnames(omb_outlays) <- c('fiscal_year', 'Agency Name', 'projection')
omb_outlays <- omb_outlays %>% mutate(office = 'OMB')

compare <- union(x = cbo_outlays, y = omb_outlays)
compare <- compare %>% filter(fiscal_year %in% c(2019, 2020, 2021, 2022, 2023))
```

```{r}
HHSonly <- budget_longform %>% filter(fiscal_year %in% c(2017) & `Agency Name`=="Social Security Administration" & expenditure != 0) 

HHS <-  HHSonly %>% select(fiscal_year, `Bureau Name`, expenditure) %>% filter(expenditure > 100000 | expenditure < 100000) %>% group_by(fiscal_year, `Bureau Name`) %>% summarise(exp=sum(expenditure))
  
projected <-  HHS %>% ggplot(aes(area=exp,  
                                 fill=`Bureau Name`, 
                                 label = `Bureau Name`)) +
  geom_treemap()  + geom_treemap_text(colour="white", 
                                      place="center", 
                                      grow = TRUE) +
      scale_y_continuous(name = "Outlays (Billions)", 
                         labels = scales::dollar_format(scale=.000001, 
                                                        accuracy = .01, 
                                                        suffix = 'B')) +
        #theme(legend.position="none") +
        labs(title = "Projected Changes in Selected Departments/Agencies",
          subtitle = "Labor's stimulus funding was short-lived,\n and DoD's expenditures decreased as wars winded down",
          caption = "Source: United States. Office of Management and Budget. Public Budget Database.",
          x = "Year",
          y = "Outlays")
ggsave(filename = 'visuals/sample.pdf', width = 11, height = 8.5)
last_plot()
```


## Federal Aid to State & Local Governments
```{r Federal Aid to State & Local Governments}
library("ggplot2")
theme_set(theme_bw())
library("sf")
raw_aid <- read_csv("raw_data/state aid - Sheet1.csv")
```


```{r}
states <- st_read('maps/cb_2017_us_state_5m.shp')

```


```{r}

```



